### ISSUE TITLE
please update the statistics

### ISSUE THREAD

**Issue by dikay0** [project-gemmi/pdb-stats#4]
Dear Marcin,

the not-the-GRC conference in Berlin begins in two weeks. Would it be possible to provide updated stats (current is until 2021)?
It'd be more relevant, and I'd point to it in my talk.

thank you,
Kay Diederichs

**Comment by wojdyr** [comment]
yes, it's time to see what has changed since 2021

I updated it on my computer. XDS is still going up :-)
![image](https://github.com/project-gemmi/pdb-stats/assets/491873/097e91d5-15e5-44a4-93f8-caa09f194825)

Before uploading it, I want to check what are "others" in various plots, perhaps new items should be listed in some categories. I'm also not sure yet what should be the starting year. Ideally, it would be configurable, but that would require some work.

**Comment by wojdyr** [comment]
I updated https://project-gemmi.github.io/pdb-stats/calendar.html
and will get to data processing stats soon.

You've seen trends.html that presents the same data as line plots?
